sudo: required
language: ruby

services:
  - docker

before_script:
  - docker build -t tod .

script:
  - docker run -v $(pwd):/tod -t tod rspec
  
notifications:
  webhooks: https://travis-buddy-service.herokuapp.com
  on_success: never # default: always  
  on_failure: always # default: always
  on_start: never   # default: never
  on_cancel: never # default: always
  on_error: never # default: always
