#!/usr/bin/env ruby

require 'clamp'
require 'tod'

Clamp do
  SECTIONS = %i(setup before script).freeze

  option ['-p', '--path'],
         'PATH',
         'Path to .travis.yml',
         default: '.travis.yml'

  parameter '[SECTION]',
            'Section from .travis.yml to be executed',
            default: 'script'

  def execute
    runner = Tod.build(from_yml: path)
    code = runner.run(section)

    exit code
  end

  # Validated section argument
  def section=(section)
    unless SECTIONS.include? section
      signal_usage_error "Unsupported section! Try #{SECTIONS * ', '}."
    end

    @section = section.to_sym
  end
end
