#!/usr/bin/env ruby

require 'clamp'
require 'tod'

Clamp do

  SECTIONS = ['script', 'before', 'install']

  option ['-p', '--path'], 'PATH', 'Path to .travis.yml', :default => '.travis.yml'

  parameter '[SECTION]', 'section from .travis.yml to execute', :default => 'script' do |s|
    unless SECTIONS.include? s
      raise ArgumentError.new "Try #{SECTIONS * ', '}."
    end
  end

  def execute
    Tod.build(from_yml: path).run(section)
  end

end
